services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    stdin_open: true
    tty: true
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge 